language: android
sudo: false
jdk:
    - oraclejdk8
before_install:
    - yes | sdkmanager "platforms;android-30"
android:
    components:
        - build-tools-29.0.2
        - android-30
        - extra-android-m2repository
script:
    - cd Pdf417MobiSample
    - ./gradlew clean assembleRelease